SELECT A.USER_ID, A.NICKNAME,
CONCAT(A.CITY, ' ', A.STREET_ADDRESS1, ' ', A.STREET_ADDRESS2) 전체주소,
CONCAT(SUBSTR(A.TLNO, 1, 3), '-', SUBSTR(A.TLNO, 4, 4), '-' , SUBSTR(A.TLNO, 8)) 전화번호 FROM USED_GOODS_USER A
JOIN USED_GOODS_BOARD B
ON B.WRITER_ID = A.USER_ID
GROUP BY B.WRITER_ID
HAVING COUNT(B.WRITER_ID) >= 3
ORDER BY A.USER_ID DESC;